# Generated by Django 5.0.7 on 2024-07-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kluster', '0002_alter_resourcestatus_requested_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LatestRsourceKindVersion',
            new_name='LatestResourceKindVersion',
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_group', models.CharField(blank=True, default='', max_length=32)),
                ('api_version', models.CharField(max_length=16)),
                ('kind', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=253)),
                ('namespace', models.CharField(blank=True, default='', max_length=63)),
                ('manifest', models.JSONField(max_length=1048576)),
                ('uid', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'db_table': 'kluster_resources',
                'unique_together': {('api_group', 'kind', 'name', 'namespace', 'uid')},
            },
        ),
    ]
