# Generated by Django 5.0.7 on 2024-07-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kluster', '0003_rename_latestrsourcekindversion_latestresourcekindversion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='api_group',
            field=models.CharField(blank=True, default='', max_length=48),
        ),
        migrations.AlterField(
            model_name='resource',
            name='api_version',
            field=models.CharField(max_length=63),
        ),
    ]
