// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.27.1
// source: api/grpc/v1/system.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pong struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pong string `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
}

func (x *Pong) Reset() {
	*x = Pong{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_v1_system_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_system_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_system_proto_rawDescGZIP(), []int{0}
}

func (x *Pong) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

type EnableOpenTelemetryCollectorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EnableOpenTelemetryCollectorRequest) Reset() {
	*x = EnableOpenTelemetryCollectorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_v1_system_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnableOpenTelemetryCollectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableOpenTelemetryCollectorRequest) ProtoMessage() {}

func (x *EnableOpenTelemetryCollectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_system_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableOpenTelemetryCollectorRequest.ProtoReflect.Descriptor instead.
func (*EnableOpenTelemetryCollectorRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_system_proto_rawDescGZIP(), []int{1}
}

type EnableOpenTelemetryCollectorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EnableOpenTelemetryCollectorResponse) Reset() {
	*x = EnableOpenTelemetryCollectorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_v1_system_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnableOpenTelemetryCollectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableOpenTelemetryCollectorResponse) ProtoMessage() {}

func (x *EnableOpenTelemetryCollectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_system_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableOpenTelemetryCollectorResponse.ProtoReflect.Descriptor instead.
func (*EnableOpenTelemetryCollectorResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_system_proto_rawDescGZIP(), []int{2}
}

type DisableOpenTelemetryCollectorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DisableOpenTelemetryCollectorRequest) Reset() {
	*x = DisableOpenTelemetryCollectorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_v1_system_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisableOpenTelemetryCollectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableOpenTelemetryCollectorRequest) ProtoMessage() {}

func (x *DisableOpenTelemetryCollectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_system_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableOpenTelemetryCollectorRequest.ProtoReflect.Descriptor instead.
func (*DisableOpenTelemetryCollectorRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_system_proto_rawDescGZIP(), []int{3}
}

type DisableOpenTelemetryCollectorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DisableOpenTelemetryCollectorResponse) Reset() {
	*x = DisableOpenTelemetryCollectorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_v1_system_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisableOpenTelemetryCollectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableOpenTelemetryCollectorResponse) ProtoMessage() {}

func (x *DisableOpenTelemetryCollectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_system_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableOpenTelemetryCollectorResponse.ProtoReflect.Descriptor instead.
func (*DisableOpenTelemetryCollectorResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_system_proto_rawDescGZIP(), []int{4}
}

type UpdateOpenTelemetryCollectorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateOpenTelemetryCollectorRequest) Reset() {
	*x = UpdateOpenTelemetryCollectorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_v1_system_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateOpenTelemetryCollectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOpenTelemetryCollectorRequest) ProtoMessage() {}

func (x *UpdateOpenTelemetryCollectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_system_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOpenTelemetryCollectorRequest.ProtoReflect.Descriptor instead.
func (*UpdateOpenTelemetryCollectorRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_system_proto_rawDescGZIP(), []int{5}
}

type UpdateOpenTelemetryCollectorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateOpenTelemetryCollectorResponse) Reset() {
	*x = UpdateOpenTelemetryCollectorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_v1_system_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateOpenTelemetryCollectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOpenTelemetryCollectorResponse) ProtoMessage() {}

func (x *UpdateOpenTelemetryCollectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_system_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOpenTelemetryCollectorResponse.ProtoReflect.Descriptor instead.
func (*UpdateOpenTelemetryCollectorResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_system_proto_rawDescGZIP(), []int{6}
}

var File_api_grpc_v1_system_proto protoreflect.FileDescriptor

var file_api_grpc_v1_system_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x64, 0x6f, 0x6b, 0x65,
	0x76, 0x79, 0x2e, 0x76, 0x31, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x1a, 0x0a, 0x04, 0x50, 0x6f, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f,
	0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x22, 0x25,
	0x0a, 0x23, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x4f, 0x70, 0x65, 0x6e, 0x54, 0x65, 0x6c, 0x65,
	0x6d, 0x65, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x26, 0x0a, 0x24, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x4f,
	0x70, 0x65, 0x6e, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x6c, 0x6c,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x26, 0x0a,
	0x24, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x4f, 0x70, 0x65, 0x6e, 0x54, 0x65, 0x6c, 0x65,
	0x6d, 0x65, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x27, 0x0a, 0x25, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65,
	0x4f, 0x70, 0x65, 0x6e, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x25,
	0x0a, 0x23, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x70, 0x65, 0x6e, 0x54, 0x65, 0x6c, 0x65,
	0x6d, 0x65, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x26, 0x0a, 0x24, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f,
	0x70, 0x65, 0x6e, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x6c, 0x6c,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xca, 0x03,
	0x0a, 0x06, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x12, 0x31, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67,
	0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0f, 0x2e, 0x64, 0x6f, 0x6b, 0x65, 0x76,
	0x79, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x6e, 0x67, 0x22, 0x00, 0x12, 0x81, 0x01, 0x0a, 0x1c,
	0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x4f, 0x70, 0x65, 0x6e, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x65,
	0x74, 0x72, 0x79, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x2e, 0x2e, 0x64,
	0x6f, 0x6b, 0x65, 0x76, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x4f,
	0x70, 0x65, 0x6e, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x6c, 0x6c,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x64,
	0x6f, 0x6b, 0x65, 0x76, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x4f,
	0x70, 0x65, 0x6e, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x6c, 0x6c,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x84, 0x01, 0x0a, 0x1d, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x4f, 0x70, 0x65, 0x6e, 0x54,
	0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x12, 0x2f, 0x2e, 0x64, 0x6f, 0x6b, 0x65, 0x76, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69,
	0x73, 0x61, 0x62, 0x6c, 0x65, 0x4f, 0x70, 0x65, 0x6e, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74,
	0x72, 0x79, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x30, 0x2e, 0x64, 0x6f, 0x6b, 0x65, 0x76, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x44,
	0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x4f, 0x70, 0x65, 0x6e, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x65,
	0x74, 0x72, 0x79, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x81, 0x01, 0x0a, 0x1c, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x4f, 0x70, 0x65, 0x6e, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x43, 0x6f,
	0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x2e, 0x2e, 0x64, 0x6f, 0x6b, 0x65, 0x76, 0x79,
	0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x70, 0x65, 0x6e, 0x54, 0x65,
	0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x64, 0x6f, 0x6b, 0x65, 0x76, 0x79,
	0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x70, 0x65, 0x6e, 0x54, 0x65,
	0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x66, 0x0a, 0x19, 0x63, 0x6f,
	0x2e, 0x75, 0x6c, 0x74, 0x61, 0x72, 0x79, 0x2e, 0x6b, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x42, 0x0b, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x75, 0x6c, 0x74, 0x61, 0x72, 0x79, 0x2f, 0x6d, 0x6f, 0x6e, 0x6f, 0x6b, 0x75,
	0x62, 0x65, 0x2f, 0x6b, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67,
	0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0xa2, 0x02, 0x09, 0x4b, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_grpc_v1_system_proto_rawDescOnce sync.Once
	file_api_grpc_v1_system_proto_rawDescData = file_api_grpc_v1_system_proto_rawDesc
)

func file_api_grpc_v1_system_proto_rawDescGZIP() []byte {
	file_api_grpc_v1_system_proto_rawDescOnce.Do(func() {
		file_api_grpc_v1_system_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_grpc_v1_system_proto_rawDescData)
	})
	return file_api_grpc_v1_system_proto_rawDescData
}

var file_api_grpc_v1_system_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_grpc_v1_system_proto_goTypes = []interface{}{
	(*Pong)(nil), // 0: dokevy.v1.Pong
	(*EnableOpenTelemetryCollectorRequest)(nil),   // 1: dokevy.v1.EnableOpenTelemetryCollectorRequest
	(*EnableOpenTelemetryCollectorResponse)(nil),  // 2: dokevy.v1.EnableOpenTelemetryCollectorResponse
	(*DisableOpenTelemetryCollectorRequest)(nil),  // 3: dokevy.v1.DisableOpenTelemetryCollectorRequest
	(*DisableOpenTelemetryCollectorResponse)(nil), // 4: dokevy.v1.DisableOpenTelemetryCollectorResponse
	(*UpdateOpenTelemetryCollectorRequest)(nil),   // 5: dokevy.v1.UpdateOpenTelemetryCollectorRequest
	(*UpdateOpenTelemetryCollectorResponse)(nil),  // 6: dokevy.v1.UpdateOpenTelemetryCollectorResponse
	(*emptypb.Empty)(nil),                         // 7: google.protobuf.Empty
}
var file_api_grpc_v1_system_proto_depIdxs = []int32{
	7, // 0: dokevy.v1.System.Ping:input_type -> google.protobuf.Empty
	1, // 1: dokevy.v1.System.EnableOpenTelemetryCollector:input_type -> dokevy.v1.EnableOpenTelemetryCollectorRequest
	3, // 2: dokevy.v1.System.DisableOpenTelemetryCollector:input_type -> dokevy.v1.DisableOpenTelemetryCollectorRequest
	5, // 3: dokevy.v1.System.UpdateOpenTelemetryCollector:input_type -> dokevy.v1.UpdateOpenTelemetryCollectorRequest
	0, // 4: dokevy.v1.System.Ping:output_type -> dokevy.v1.Pong
	2, // 5: dokevy.v1.System.EnableOpenTelemetryCollector:output_type -> dokevy.v1.EnableOpenTelemetryCollectorResponse
	4, // 6: dokevy.v1.System.DisableOpenTelemetryCollector:output_type -> dokevy.v1.DisableOpenTelemetryCollectorResponse
	6, // 7: dokevy.v1.System.UpdateOpenTelemetryCollector:output_type -> dokevy.v1.UpdateOpenTelemetryCollectorResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_grpc_v1_system_proto_init() }
func file_api_grpc_v1_system_proto_init() {
	if File_api_grpc_v1_system_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_grpc_v1_system_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pong); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_v1_system_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnableOpenTelemetryCollectorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_v1_system_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnableOpenTelemetryCollectorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_v1_system_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DisableOpenTelemetryCollectorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_v1_system_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DisableOpenTelemetryCollectorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_v1_system_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateOpenTelemetryCollectorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_v1_system_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateOpenTelemetryCollectorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_grpc_v1_system_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_v1_system_proto_goTypes,
		DependencyIndexes: file_api_grpc_v1_system_proto_depIdxs,
		MessageInfos:      file_api_grpc_v1_system_proto_msgTypes,
	}.Build()
	File_api_grpc_v1_system_proto = out.File
	file_api_grpc_v1_system_proto_rawDesc = nil
	file_api_grpc_v1_system_proto_goTypes = nil
	file_api_grpc_v1_system_proto_depIdxs = nil
}
