apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: polykube
  labels:
    org: home
spec:
  secretName: polykube-https-tls
  dnsNames:
    - kafka.{{ .Values.domains.root }}
    - minio.{{ .Values.domains.root }}
  issuerRef:
    name: aws-route53
    kind: ClusterIssuer
---
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: polykube
  annotations:
    external-dns.kubernetes.io/private: 'true'
    #external-dns.kubernetes.io/public: 'true'
  labels:
    org: home
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - kafka.{{ .Values.domains.root }}
        - minio.{{ .Values.domains.root }}
      port:
        name: http
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true
    - hosts:
        - kafka.{{ .Values.domains.root }}
        - minio.{{ .Values.domains.root }}
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        credentialName: polykube-https-tls
        mode: SIMPLE
---