apiVersion: v1
kind: Secret
metadata:
  name: minio
  labels:
    app: minio
    org: home
immutable: true
stringData:
  MINIO_ROOT_PASSWORD: ''
type: Opaque
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  labels:
    app: minio
    org: home
spec:
  minReadySeconds: 10
  selector:
    matchLabels:
      app: minio
      org: home
  serviceName: minio
  template:
    metadata:
      labels:
        app: minio
        org: home
    spec:
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 10
      containers:
        - name: minio
          image: {{ .Values.minio.image.repository }}:{{ .Values.minio.image.tag }}
          args:
            - server
            - /data
            - --console-address
            - 0.0.0.0:9001
          env:
            - name: MINIO_DOMAIN
              value: minio.mk.dokevy.io
            - name: MINIO_ROOT_USER
              value: admin
            - name: MINIO_SERVER_URL
              value: http://minio:9000
            - name: MINIO_BROWSER_REDIRECT_URL
              value: https://minio.mk.dokevy.io/ui/
          envFrom:
            - secretRef:
                name: minio
          livenessProbe:
            exec:
              command: [ "mc", "ready", "local" ]
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 3
          ports:
            - containerPort: 9000
              name: server
            - containerPort: 9001
              name: console
          securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: data
              mountPath: /data
            - name: tmp
              mountPath: /tmp/.mc
      volumes:
        - name: tmp
          emptyDir:
            sizeLimit: 64Ki
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ 'ReadWriteOnce' ]
        #storageClassName: hostpath
        storageClassName: local-path
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app: minio
    org: home
spec:
  clusterIP: None
  ports:
    - port: 9000
      name: server
    - port: 9001
      name: console
  selector:
    app: minio
    org: home
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: minio
spec:
  gateways:
    - monokube
  hosts:
    - minio.{{ .Values.domains.root }}
  http:
    - match:
        - uri:
            prefix: /ui/
      rewrite:
        uri: /
      route:
        - destination:
            host: minio
            port:
              number: 9001
    - route:
        - destination:
            host: minio
            port:
              number: 9000
---